import { useCallback, useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { deleteListing, listOwnerListings, updateListing } from '@/api/client';
import type { ApiListing } from '@/api/types';
import { useAuth } from '@/auth/AuthContext';
import { EmptyState, ErrorState, LoadingState } from '@/components/StateView';
import { useTheme } from '@/theme/ThemeContext';
import { formatPrice } from '@/components/PropertyCard';

export default function ManageListingsScreen() {
  const { colors, styles } = useTheme(); const router = useRouter(); const { user } = useAuth(); const [listings, setListings] = useState<ApiListing[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<string | null>(null); const [title, setTitle] = useState(''); const [price, setPrice] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(''); try { setListings((await listOwnerListings()).items); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Your listings could not be loaded.'); } finally { setLoading(false); } }, [user]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const startEdit = (listing: ApiListing) => { setEditing(listing.id); setTitle(listing.title); setPrice(String(listing.price)); setNotice(''); };
  const save = async (id: string) => { const amount = Number(price); if (!title.trim() || !Number.isFinite(amount)) { setError('Enter a valid title and price.'); return; } try { await updateListing(id, { title: title.trim(), price: amount }); setListings((current) => current.map((item) => item.id === id ? { ...item, title: title.trim(), price: amount } : item)); setEditing(null); setNotice('Listing updated through the Umutungo API.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Listing could not be updated.'); } };
  const remove = async (id: string) => { try { await deleteListing(id); setListings((current) => current.filter((item) => item.id !== id)); setNotice('Listing deleted through the Umutungo API.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Listing could not be deleted.'); } };
  if (!user) return <View style={[styles.screen, styles.safeContent]}><Text style={styles.heading}>Sign in required</Text><Pressable style={styles.button} onPress={() => router.push('/auth/sign-in')}><Text style={styles.buttonText}>Sign in</Text></Pressable></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.safeContent}><Pressable onPress={() => router.back()}><Text style={{ color: colors.green, fontWeight: '800' }}>‹ Back</Text></Pressable><Text style={styles.title}>Manage listings</Text>{notice && <Text style={{ color: colors.greenDark, fontWeight: '700' }}>{notice}</Text>}{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={() => void load()} /> : listings.length === 0 ? <EmptyState title="No listings yet" message="Create your first listing from the profile tab." /> : <View style={{ gap: 12 }}>{listings.map((listing) => <View key={listing.id} style={[styles.card, { gap: 8 }]}>{editing === listing.id ? <><TextInput style={styles.input} value={title} onChangeText={setTitle} /><TextInput style={styles.input} value={price} onChangeText={setPrice} keyboardType="numeric" /><View style={{ flexDirection: 'row', gap: 8 }}><Pressable style={[styles.button, { flex: 1 }]} onPress={() => void save(listing.id)}><Text style={styles.buttonText}>Save</Text></Pressable><Pressable style={[styles.secondaryButton, { flex: 1 }]} onPress={() => setEditing(null)}><Text style={styles.secondaryText}>Cancel</Text></Pressable></View></> : <><Text style={styles.heading}>{listing.title}</Text><Text style={styles.body}>{listing.sector}, {listing.district} · {formatPrice(listing)}</Text><Text style={styles.muted}>{listing.status}</Text><View style={{ flexDirection: 'row', gap: 16 }}><Pressable onPress={() => startEdit(listing)}><Text style={{ color: colors.green, fontWeight: '800' }}>Edit</Text></Pressable><Pressable onPress={() => void remove(listing.id)}><Text style={{ color: colors.danger, fontWeight: '800' }}>Delete</Text></Pressable></View></>}</View>)}</View>}</ScrollView>;
}
