import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { registerAccount, requestOtp } from '@/api/client';
import type { UserRole } from '@/api/types';
import { useTheme } from '@/theme/ThemeContext';

const roles: Array<{ label: string; value: UserRole }> = [{ label: 'Client', value: 'client' }, { label: 'Tenant', value: 'tenant' }, { label: 'Property owner', value: 'property_owner' }, { label: 'Komisiyoneri', value: 'komisiyoneri' }];
export default function RegisterScreen() {
  const { colors, styles } = useTheme();
  const router = useRouter();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [role, setRole] = useState<UserRole>('client'); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!name.trim() || phone.replace(/\D/g, '').length < 9) { setError('Enter your name and a valid Rwanda phone number.'); return; } setBusy(true); setError(''); try { const result = await registerAccount({ name: name.trim(), email: email.trim(), phone: phone.trim(), role }); const otp = await requestOtp(phone.trim()); setNotice(`${result.message}. ${otp.development_code ? `Development code: ${otp.development_code}` : 'Check your SMS for the code.'}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Account could not be created.'); } finally { setBusy(false); } };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.safeContent} keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text style={{ color: colors.green, fontWeight: '800' }}>‹ Back</Text></Pressable><Text style={styles.brand}>UMUTUNGO</Text><Text style={styles.title}>Create your account.</Text><Text style={styles.body}>Your account is created by the existing Umutungo API and verified with phone OTP.</Text>{error && <Text style={styles.error}>{error}</Text>}{notice && <Text style={[styles.body, { color: colors.greenDark }]}>{notice}</Text>}<View style={{ gap: 10 }}><Text style={styles.label}>Full name</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Your full name" placeholderTextColor={colors.muted} /><Text style={styles.label}>Email address</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor={colors.muted} keyboardType="email-address" autoCapitalize="none" /><Text style={styles.label}>Rwanda phone number</Text><TextInput style={styles.input} value={phone} onChangeText={setPhone} placeholder="+250 7XX XXX XXX" placeholderTextColor={colors.muted} keyboardType="phone-pad" /><Text style={styles.label}>I am a</Text><View style={{ gap: 8 }}>{roles.map((item) => <Pressable key={item.value} style={[styles.secondaryButton, role === item.value && { borderColor: colors.green, backgroundColor: colors.greenSoft }]} onPress={() => setRole(item.value)}><Text style={styles.secondaryText}>{item.label}</Text></Pressable>)}</View><Pressable style={styles.button} disabled={busy} onPress={() => void submit()}><Text style={styles.buttonText}>{busy ? 'Creating...' : 'Create account'}</Text></Pressable></View></ScrollView></KeyboardAvoidingView>;
}
